### ISSUE TITLE
ValueError in running RGA.py

### ISSUE THREAD

**Issue by owaski** [futianfan/reinforced-genetic-algorithm#3]
I loaded the pre-trained checkpoint and evaluate on a set of different protein targets and after several rounds it output the following error. 

Traceback (most recent call last):
  File "RGA.py", line 994, in <module>
    pdbqtvina_list = pdbqtvina_list)
  File "/home/siqiouyang/work/projects/GEKO/baselines/reinforced-genetic-algorithm/model.py", line 324, in forward_ligand_list
    feature_list = featurize_receptor_and_ligand_list(name_of_receptor, pdbqtvina_list)
  File "/home/siqiouyang/work/projects/GEKO/baselines/reinforced-genetic-algorithm/model.py", line 204, in featurize_receptor_and_ligand_list
    ligand_atom_idx, ligand_positions, ligand_mask = pdbqtvina2feature(pdbqt_file)
  File "/home/siqiouyang/work/projects/GEKO/baselines/reinforced-genetic-algorithm/model.py", line 167, in pdbqtvina2feature
    line_indx = lines.index("MODEL 2")
ValueError: 'MODEL 2' is not in list

It seems to be pdbqt file error, but I checked the results directory the pdbqt files are have string "MODEL 2" inside. Could you please help me resolve this issue?

**Comment by futianfan** [comment]
hi Siqi, I tried it, but did not find the same error, which commandline do you use? will take a deep look and let you know later. thanks!

**Comment by owaski** [comment]
python RGA.py \
    --root_output_folder ./output \
    --number_of_mutants_first_generation 50 \
    --number_of_crossovers_first_generation 50 \
    --number_of_mutants 50 \
    --number_of_crossovers 50 \
    --top_mols_to_seed_next_generation 50 \
    --number_elitism_advance_from_previous_gen 50 \
    --number_elitism_advance_from_previous_gen_first_generation 10 \
    --diversity_mols_to_seed_first_generation 10 \
    --diversity_seed_depreciation_per_gen 10 \
    --num_generations 10 \
    --mgltools_directory ./mgltools_x86_64Linux2_1.5.6/ \
    --number_of_processors -1 \
    --scoring_choice VINA \
    --LipinskiLenientFilter \
    --start_a_new_run \
    --rxn_library click_chem_rxns \
    --selector_choice Rank_Selector \
    --dock_choice VinaDocking \
    --max_variants_per_compound 5 \
    --redock_elite_from_previous_gen False \
    --generate_plot True \
    --reduce_files_sizes True \
    --use_docked_source_compounds True  
    
Also, I changed the 'receptor_info_list' in RGA.py and model.py to be my protein targets.

**Comment by owaski** [comment]
A side fact is that this happens after like 5 generations, not at the beginning.

**Comment by owaski** [comment]
@futianfan Another confusing part is that, in your paper, it says the 0th generation is initialized from molecules from ZINC. I did see the .smi files from ZINC, but unclear of how you use it.

**Comment by futianfan** [comment]
> @futianfan Another confusing part is that, in your paper, it says the 0th generation is initialized from molecules from ZINC. I did see the .smi files from ZINC, but unclear of how you use it.

a random subset of ZINC is used as initialization.

**Comment by futianfan** [comment]
> python RGA.py --root_output_folder ./output --number_of_mutants_first_generation 50 --number_of_crossovers_first_generation 50 --number_of_mutants 50 --number_of_crossovers 50 --top_mols_to_seed_next_generation 50 --number_elitism_advance_from_previous_gen 50 --number_elitism_advance_from_previous_gen_first_generation 10 --diversity_mols_to_seed_first_generation 10 --diversity_seed_depreciation_per_gen 10 --num_generations 10 --mgltools_directory ./mgltools_x86_64Linux2_1.5.6/ --number_of_processors -1 --scoring_choice VINA --LipinskiLenientFilter --start_a_new_run --rxn_library click_chem_rxns --selector_choice Rank_Selector --dock_choice VinaDocking --max_variants_per_compound 5 --redock_elite_from_previous_gen False --generate_plot True --reduce_files_sizes True --use_docked_source_compounds True
> 
> Also, I changed the 'receptor_info_list' in RGA.py and model.py to be my protein targets.

it would be great if you could share the targets you use so that I can run it too, thanks

**Comment by futianfan** [comment]
@owaski fixed it and let me know through email, so i close the issue.
