### ISSUE TITLE
Docking coordinates for pdb proteins

### ISSUE THREAD

**Issue by qky18** [futianfan/reinforced-genetic-algorithm#6]
Hi @futianfan , thanks for sharing this wonderful piece of work!
I'd like to reproduce the RGA experiment results, but found that pre-specified `center_x, center_y, center_z` would be needed for each of the 10 protein pdbs. Could you please share the docking coordinates that are used for each pdb file? Many thanks in advance!

**Comment by futianfan** [comment]
Thanks for your interest! Here are the coordinates: 

(1) 4r6e: Human artd1, catalytic domain in complex with inhibitor niraparib, pocket center is (-70.8, 21.8, 28.3); 
(2) 3pbl: structure of the human dopamine D3 receptor in complex with eticlopride, the pocket center is (9.0, 22.5, 26.0);  
(3) 1iep: crystal structure of the C-ABL kinase domain in complex with STI-571; the pocket center is (15.6, 53.4, 15.5); 
(4) 2rgp: structure of EGFR in complex with hydrazone, a potent dual inhibitor, the pocket center is (16.3, 34.9, 92.0); 
(5) 3eml, the 2.6 A Crystal Structure of a human A2A Adenosine receptor bound to ZM241385, the pocket center is (-9.1, -7.1, 55.8); 
(6) 3ny8: Crystal structure of the human beta2 adrenergic receptor in complex with the inverse agonist ICI 118,551, 
the pocket center is (2.2, 4.7, 51.4); 
(7) 4rlu, Crystal Structure of (3R)-hydroxyacyl-ACP dehydratase HadAB hetero-dimer from Mycobacterium tuberculosis complexed with 2',4,4'-trihydroxychalcone, the pocket center is (-0.7, 22.8, -31.3); 
(8) 4unn, Mtb TMK in complex with compound 8, the pocket center is (5.7, 18.2, -7.4); 
(9) 5mo4, ABL1 kinase (T334I\_D382N) in complex with asciminib and nilotinib, the pocket center is (-44.9, 20.5, 8.5);
(10) 7l11, CRYSTAL STRUCTURE OF THE SARS-COV-2(2019-NCOV) MAIN PROTEASE IN COMPLEX WITH COMPOUND 5
the SARS-COV-2(2019-NCOV) main protease in complex with compound 5, the pocket center is (-21.8, -4.2, -28.0). 

We are following https://tdcommons.ai/functions/oracles/#docking-scores, where you can also download the target proteins.

**Comment by qky18** [comment]
Thank you so much for the immediate response! This really helps a lot. I'll try experimenting with these pocket centers.

**Comment by qky18** [comment]
Hello @futianfan  sorry for asking again. I noticed that some errors occurred when I tried to parse pdb `3pbl.pdb`. The error message was as follows when I ran `pdb = Chem.MolFromPDBFile('./reinforced-genetic-algorithm/pdb/3pbl.pdb')`:
```
****
Post-condition Violation
Element 'A' not found
Violation occurred on line 93 in file [/project/build/temp.linux-x86_64-cpython-39/rdkit/Code/GraphMol/PeriodicTable.h](https://vscode-remote+ssh-002dremote-002b3090-002d3.vscode-resource.vscode-cdn.net/project/build/temp.linux-x86_64-cpython-39/rdkit/Code/GraphMol/PeriodicTable.h)
Failed Expression: anum > -1
****
```
I tried to download this pdb from RCSB, but it seems that the downloaded file does not align with the one provided in `pdb` folder. I was wondering what might be causing this error. Am I doing it right? Or is there anything wrong with the pdb file? Thank you!

**Comment by futianfan** [comment]
i guess our pdb structure is a subset of the whole protein structure, it is obtained by removing the atoms out of the binding box. thx for your interest!

**Comment by qky18** [comment]
> i guess our pdb structure is a subset of the whole protein structure, it is obtained by removing the atoms out of the binding box. thx for your interest!

Does that mean if I'd like to parse the pdb and then perform docking, I just need to download the whole structure, and find the pocket center for this original protein?
<img width="334" alt="image" src="https://github.com/futianfan/reinforced-genetic-algorithm/assets/48824043/d2a72786-862b-44b3-bb69-65884e384ad1">
I found the transformation from original protein (colored in brown) to processed pocket (colored in green) a bit complicated. How may I obtain the original pocket center?

**Comment by qky18** [comment]
Also, I found that `4r6e.pdbqt` seemed to be missing in `pdb` folder, and simply trying `obabel 4r6e.pdb -O 4r6e.pdbqt` failed during vina docking, throwing `PDBQT parsing error: Unknown or inappropriate tag found in rigid receptor. > ROOT`.

**Comment by qky18** [comment]
I fixed the problems with `3pbl` and `4r6e` by downloading them from RCSB and performing alignment (if need be) via PyMOL. Thanks again for your help!
